In [ ]:
Consider the below code to answer further questions:

import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list 
is a NumPy array object.

You can print the data types of both variables using the type() function in Python:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_)) # Output: <class 'list'>
print(type(array_list)) # Output: <class 'numpy.ndarray'>


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
for element in list_:
    print(type(element))

# print data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
Yes, there will be a difference in the data type of the elements present in list_ and array_list after the change.
In this code, we are creating a new NumPy array array_list from the elements of the list_ variable and specifying the data 
type as int using the dtype parameter. This means that all the elements in the new array will be converted to integers.

Here's the code to print the data type of each element present in both the list_ and array_list variables:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# print data type of each element in list_
for element in list_:
    print(type(element))

# print data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

# create a NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# find the shape of the array
shape = num_array.shape

# find the size of the array
size = num_array.size

# print the shape and size of the array
print("Shape of the array:", shape)
print("Size of the array:", size)


Shape of the array: (3, 3)
Size of the array: 9


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [ ]:
import numpy as np

# create a 3x3 matrix of zeros using the zeros() function
zeros_array = np.zeros((3, 3))

# print the zeros array
print(zeros_array)


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [5]:
import numpy as np

# create an identity matrix of shape (5,5) using the identity() function
identity_array = np.identity(5)

# print the identity matrix
print(identity_array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
